### ISSUE TITLE
邀请协助测试内测版本Varlet-Cli

### ISSUE THREAD

**Issue by haoziqaq** [Lastly1999/fast-deisgn#1]
如题，内测版本

```
yarn add @varlet/cli@alpha
```

主要改动

- Webpack5 -> Vite

主要测试内容

- dev命令是否有效
- build命令是否有效，及其产出(site)是否可用
- compile命令是否有效，及其产出是否可用(es, umd)

有空可以尝试迁移，没有做破坏性修改，理论上可以无缝迁移，有问题再沟通。

**Comment by Lastly1999** [comment]
好的，将在这两天内进行迁移测试
